### ISSUE TITLE
"Midair" items don't update properly.

### ISSUE THREAD

**Issue by hifoomin** [quickstraw/StormyItems#4]
Self explanatory, they don't update because RecalculateStats() isn't called when hitting the ground, making you keep the stats until the next RecalculateStats() is called. This can be pretty easily fixed:

```cs
On.RoR2.CharacterMotor.OnLanded += CharacterMotor_OnLanded;
On.RoR2.CharacterMotor.OnLeaveStableGround += CharacterMotor_OnLeaveStableGround;

        private void CharacterMotor_OnLeaveStableGround(On.RoR2.CharacterMotor.orig_OnLeaveStableGround orig, CharacterMotor self)
        {
            self.body.statsDirty = true;
            orig(self);
        }

        private void CharacterMotor_OnLanded(On.RoR2.CharacterMotor.orig_OnLanded orig, CharacterMotor self)
        {
            self.body.statsDirty = true;
            orig(self);
        }
```

This essentially queues a RecalculateStats() to happen about a frame after you leave stable ground or hit the ground.

**Comment by quickstraw** [comment]
Thanks for the detailed report! I'll add it in whenever I get the chance.

**Comment by quickstraw** [comment]
I finally got some time to update. Thanks for your help.
