### ISSUE TITLE
0.9.9 or 0.9.10 Drone Coolant

### ISSUE THREAD

**Issue by OrokinLonewolf** [quickstraw/StormyItems#5]
I think the recent update bugged Illegal Drone Coolant and made the drone's version a white item that can be picked up by the player, and the normal green item version is missing from player arsenal.

https://imgur.com/a/bOtkLJD

**Comment by OrokinLonewolf** [comment]
Update, the green item not appearing was my own fault. You can ignore that part. The drone's item is still droppable, though.

**Comment by quickstraw** [comment]
Thanks for letting me know! It should be fixed in the latest update I just put out (0.9.11).
